### PR TITLE
#621: fix heal button not editing self

### LINKED ISSUE #621: Using last room action to heal at rest site doesn't disable heal button

### PR DESCRIPTION
**Pull request by ntseng**
Summary
-------
- fix heal button not editing self

Local Tests Performed
---------------------
- used the rest button in a rest site during adventure

Issue
-----
Closes #621

### CODE REVIEW

File: Source/Buttons/rest.js [hunk 1]
```diff
@@ -27,7 +28,7 @@ module.exports = new Button(customId,
 		let components = interaction.message.components;
 		if (remainingActions < 1) {
 			components = editButtons(components, {
-				[customId]: { preventUse: true, label: "The party rested", emoji: "✔️" },
+				[`${customId}${SAFE_DELIMITER}${healPercent}`]: { preventUse: true, label: "The party rested", emoji: "✔️" },
```
Comment (doubledh) [inline Source/Buttons/rest.js:31]: Is there a funny interaction where taking on "restless" challenge causes this button-name to change in a way that this fix misses it?

**Review by doubledh — APPROVED** [review]

File: Source/Buttons/rest.js (hunk 1 above)
Comment (ntseng) [reply Source/Buttons/rest.js:31]: I would be surprised if so, the change that caused the bug was to show the heal percent to the players on the button's label (ie, Restless's heal penalty should already be baked in by this point).

Comment (ntseng) [reply Source/Buttons/rest.js:31]: pinging again because i realized i didn't answer the question and in case the edit didn't ping
