### PR TITLE
v0.9.0 Fix (#400)

### LINKED ISSUE #400: Reduce maximum delvers per adventure to 8
If a party has more than 8 delvers, the UI would break if a delver tried to ready a move that can target all combatants in a fight with an enemy with a 2n outnumbering ratio (9 delvers + 18 enemies > 25 select options/embed fields).

Other notable thresholds for player count:
5 delvers - allows up to 4n outnumber ratio
4 delvers - allows up to 5n outnumber ratio

Because we may be tuning this value and it may be used in more than one place, this refactor should declare a game value constant (in `helpers.js`) that can be imported to where-ever it's needed.

### PR DESCRIPTION
**Pull request by ntseng**
- reduced max delver count to 8

### CODE REVIEW

File: Source/Buttons/join.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ module.exports.execute = async (interaction, [guildId, adventureId, context]) =>
 							embeds = [recruitMessage.embeds[0].spliceFields(0, 1, { name: `${adventure.delvers.length} Party Member${adventure.delvers.length == 1 ? "" : "s"}`, value: partyList })];
 						}
 						let components = recruitMessage.components;
-						if (adventure.delvers.length > 11) {
+						if (adventure.delvers.length === maxDelverCount) {
```
Comment (doubledh) [inline Source/Buttons/join.js:50]: between this change going from > to === and the previous staying with <, I get the feeling that at least one race condition (or perhaps there was already one available as well) is possible from this piece of code

I won't let that block this PR, though

**Review by doubledh — APPROVED** [review]
LGTM, left a note about a possible race-condition spot

File: Source/Buttons/join.js (hunk 1 above)
Comment (ntseng) [reply Source/Buttons/join.js:50]: The second conditional is only for updating the ui. I think even if the ui gets desynced, the first conditional should still catch extra players joining, right?

**Review by bobaguardian — APPROVED** [review]
