### PR TITLE
v0.7.0 Feature (#47) and Fixes

### LINKED ISSUE #47: difficulty options
- Imperfect Inversion: Removing debuffs by gaining buffs is only half as effective
- Poor Enemies: Less gold from fights
- Stingy Merchants: Higher prices
- Empowered Enemies: Randomized buffs for certain enemies
- Restless: heal less at rest sites
- Can't Turn: one fewer room choices rolled
- Damaged Goods: weapons bought from merchants aren't full uses

### PR DESCRIPTION
**Pull request by ntseng**
- recruit message lists adventure's challenges
- restless challenge
- fixed crash on getWeaponCapacity without Can't Hold All this Value

### CODE REVIEW

File: Source/Selects/challenge.js [hunk 1]
```diff
@@ -9,13 +9,34 @@ module.exports.execute = (interaction, args) => {
...
+			interaction.channel.send({ content: "Starting Challenges have been cleared for this adventure." });
 		} else {
 			interaction.values.forEach(challengeName => {
 				const challenge = getChallenge(challengeName);
 				adventure.challenges[challengeName] = { intensity: challenge.startingValue, duration: challenge.duration };
 			})
-			interaction.reply({ content: `The following challenges have been added to this adventure: ${interaction.values.join(", ")}` });
+			interaction.channel.fetchStarterMessage().then(starterMessage => {
+				let embed = starterMessage.embeds[0];
+				let challengesText = Object.keys(adventure.challenges).join(", ");
```
Comment (doubledh) [inline Source/Selects/challenge.js]: I can imagine challenges having commas inside challenge names, so it might look funny in the future, but that problem won't actively break anything for now

**Review by doubledh — APPROVED** [review]
LGTM

File: Source/Selects/challenge.js (hunk 1 above)
Comment (ntseng) [reply Source/Selects/challenge.js]: In that case, we might want to have challenge names read as bold or italics (double or single asterisk in discord markdown respectively).

Comment (doubledh) [reply Source/Selects/challenge.js]: yeah I was thinking of quoting the challenge names ... bold/italics means that only the separating commas would appear nonbolded/nonitalicized to let a player know the difference
