### PR TITLE
v0.9.0 Content (#95), Balance, and Fixes

### LINKED ISSUE #95: Modifiers: Stasis/Isolation
- Neither buffs nor debuffs
- 0 turn decrement

Stasis: Prevents the next <stack size> removals (excluding natural expiration) of buffs or debuffs

Isolation: Prevents the next <stack size> additions of buffs or debuffs

### PR DESCRIPTION
**Pull request by ntseng**
- implemented stasis and oblivious modifiers
- promotion of Progress now adds a stack of Stasis
- fixed outdated arguments on modifier inversion, element shift crit, cloak, thick cloak

### CODE REVIEW

File: Source/Enemies/royalslime.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ function elementShift(target, user, isCrit, adventure) {
 	user.element = elementsList()[generateRandomNumber(adventure, elementsList().length, "battle")];
 	if (isCrit) {
 		addModifier(user, { name: `${user.element} Absorb`, stacks: 5 });
-		removeModifier(user, "Stagger", 1);
+		removeModifier(user, { name: "Stagger", stacks: 1 });
```
Comment (doubledh) [inline Source/Enemies/royalslime.js:27]: is there a reason why the user wasn't bundled into the argument-that's-now-an-object? Is there a name for this pattern that seems to have a reasonable boundary?

**Review by doubledh — APPROVED** [review]
Noice. One question

File: Source/Enemies/royalslime.js (hunk 1 above)
Comment (ntseng) [reply Source/Enemies/royalslime.js:27]: I'm not aware of the name if there is one. The main concern of this pattern is that `user` is a standalone entity (that we may query a database) and that the stuff in the object is ephemeral (not expected to survive the function).
