### PR TITLE
Ntseng/issue268

### LINKED ISSUE #268: Crash on room vote
Screenshot 2022-03-15 193346
Screenshot 2022-03-15 193356

### PR DESCRIPTION
**Pull request by ntseng**
Move race condition was already address (lol). Was not able to test race condition solo however.

### CODE REVIEW

File: Source/Rooms/_roomDictionary.js [hunk 1]
```diff
@@ -67,9 +67,8 @@ exports.manufactureRoomTemplate = function (type, adventure) {
 
 	if (!roomPool) {
```
Comment (doubledh) [inline Source/Rooms/_roomDictionary.js:68]: is this clause to go to a battle by default? (like at the start of every game)

File: Source/Buttons/continue.js [hunk 2]
```diff
@@ -1,6 +1,7 @@
 const { nextRoom, getAdventure } = require('../adventureDAO.js');
 const Button = require('../../Classes/Button.js');
 const { MessageActionRow, MessageButton } = require('discord.js');
+const { SAFE_DELIMITER } = require('../../helpers.js');
```
Comment (doubledh) [inline Source/Buttons/continue.js:4]: does this "continue" button show up if there's only one option?

**Review by doubledh — COMMENTED** [review]
Looks good! I've just got a couple of questions that don't directly have to do with the changes

File: Source/Rooms/_roomDictionary.js (hunk 1 above)
Comment (ntseng) [reply Source/Rooms/_roomDictionary.js:68]: It's a contingency for if roomCandidates becomes unreadable. Default combat at start of game is set in /Buttons/ready.js

File: Source/Buttons/continue.js (hunk 2 above)
Comment (ntseng) [reply Source/Buttons/continue.js:4]: Yes. Instead of requiring all players to vote for the one option, having the leader confirm when to move on is a little faster.

**Review by doubledh — APPROVED** [review]
LGTM ("Looks good to me"; the phrase that either means your code has been properly looked at

or completely incompletely skimmed xD)
